networks:
  kafka-network:
    driver: bridge

services:
  control-center:
    image: confluentinc/cp-enterprise-control-center:7.7.1
    container_name: control-center
    networks:
      - kafka-network
    ports:
      - "9021:9021"
    environment:
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8081"
      CONTROL_CENTER_REST_LISTENERS: "http://0.0.0.0:9021"
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker1:29092,broker2:39092,broker3:49092'
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'kafka-connect1:8083,kafka-connect2:8083'
      CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: '/connectors'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry1:8081,http://schema-registry2:8082"
      CONTROL_CENTER_REPLICATION_FACTOR: 3
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 12
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATIONS: 3
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 3
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 3
      CONFLUENT_METRICS_TOPIC: '_confluent-metrics'
      CONFLUENT_METRICS_TOPIC_PARTITIONS: 12
      CONFLUENT_METRICS_TOPIC_REPLICATION: 3
      CONFLUENT_METRICS_REPORTER_TOPIC_MIN_INSYNC_REPLICAS: 2
      CONTROL_CENTER_UI_AUTOUPDATE_ENABLE: false
      CONTROL_CENTER_UI_CONTROLLER_CHART_ENABLE: true
      CONTROL_CENTER_USAGE_DATA_COLLECTION_ENABLE: false
      CONTROL_CENTER_COMMAND_TOPIC: '_confluent-command'
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 3
