- name: Create directory for properties files
  file:
    path: /engn/confluent/properties
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    recurse: yes

- name: Deploy schema-registry.properties.j2 to instance
  template:
    src: schema-registry.properties{{ groups['schema_registries'].index(inventory_hostname) + 1 }}.j2
    dest: /engn/confluent/properties/schema-registry.properties
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Deploy schema-registry-log4j.properties.j2 to instance
  template:
    src: schema-registry-log4j.properties.j2
    dest: /engn/confluent/properties/schema-registry-log4j.properties
    owner: ubuntu
    group: ubuntu         
    mode: '0644'            


- name: Create directory for scripts files
  file:
    path: /engn/confluent/scripts
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    recurse: yes

- name: Deploy start-schema-registry.sh.j2 to instance
  template:
    src: start-schema-registry{{ groups['schema_registries'].index(inventory_hostname) + 1 }}.sh.j2
    dest: /engn/confluent/scripts/start-schema-registry.sh
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    
- name: Deploy stop-schema-registry.sh.j2 to instance
  template:
    src: stop-schema-registry.sh.j2
    dest: /engn/confluent/scripts/stop-schema-registry.sh
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Run start-schema-registry.sh
  command: /engn/confluent/scripts/start-schema-registry.sh
  become: yes